import { mutation } from "./_generated/server";

// Seed function to add sample recipes
// Run this via: npx convex run seed:seedRecipes
export const seedRecipes = mutation({
  args: {},
  handler: async (ctx) => {
    // First, check if we have a user to use as chef
    const users = await ctx.db.query("users").take(1);
    if (users.length === 0) {
      throw new Error("No users found. Please create a user first.");
    }
    const chefId = users[0]._id;

    // Delete all existing recipes so we can re-seed cleanly
    const existingRecipes = await ctx.db.query("recipes").collect();
    for (const recipe of existingRecipes) {
      await ctx.db.delete(recipe._id);
    }

    const sampleRecipes = [
      {
        title: "Jollof Rice",
        description: "A beloved West African one-pot rice dish cooked in a rich, smoky tomato sauce with aromatic spices. Every bite is packed with deep, layered flavour.",
        imageUrl: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800",
        country: "Nigeria",
        countryFlag: "🇳🇬",
        chefId,
        tags: ["Halal", "Vegan"],
        category: "Dinner",
        rating: 4.8,
        reviewCount: 2847,
        prepTime: 1200,
        cookTime: 2700,
        servings: 6,
        ingredients: [
          { name: "Long grain rice", amount: "3 cups" },
          { name: "Tomato paste", amount: "4 tbsp" },
          { name: "Fresh tomatoes", amount: "6 large" },
          { name: "Scotch bonnet pepper", amount: "2" },
          { name: "Onions", amount: "2 large" },
          { name: "Vegetable oil", amount: "1/3 cup" },
          { name: "Chicken stock", amount: "3 cups" },
          { name: "Bay leaves", amount: "3" },
          { name: "Thyme", amount: "1 tsp" },
          { name: "Curry powder", amount: "1 tsp" },
        ],
        instructions: [
          "Blend the tomatoes, scotch bonnet peppers, and one onion until smooth. Set aside.",
          "Heat oil in a large pot over medium heat. Dice the remaining onion and fry until golden brown.",
          "Add tomato paste and fry for 3-4 minutes until it darkens in colour.",
          "Pour in the blended tomato mixture and cook on medium heat for 25-30 minutes until the oil floats to the top.",
          "Add chicken stock, bay leaves, thyme, curry powder, and salt to taste. Bring to a boil.",
          "Wash and add the rice. Stir well, then cover tightly with foil and a lid. Cook on low heat for 30 minutes.",
          "Remove from heat, fluff with a fork, and let it steam for 10 more minutes before serving.",
        ],
        savedBy: [],
        createdAt: Date.now(),
      },
      {
        title: "Suya Skewers",
        description: "Smoky, spicy Nigerian street-food beef skewers coated in a fragrant ground peanut and chilli spice mix called yaji.",
        imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
        country: "Nigeria",
        countryFlag: "🇳🇬",
        chefId,
        tags: ["Halal", "Protein"],
        category: "Dinner",
        rating: 4.6,
        reviewCount: 1543,
        prepTime: 1800,
        cookTime: 900,
        servings: 4,
        ingredients: [
          { name: "Beef sirloin", amount: "2 lbs" },
          { name: "Ground peanuts", amount: "1 cup" },
          { name: "Cayenne pepper", amount: "2 tbsp" },
          { name: "Onion powder", amount: "1 tbsp" },
          { name: "Garlic powder", amount: "1 tbsp" },
          { name: "Ginger powder", amount: "1 tsp" },
          { name: "Paprika", amount: "1 tbsp" },
          { name: "Vegetable oil", amount: "3 tbsp" },
          { name: "Bouillon cube", amount: "1" },
          { name: "Salt", amount: "to taste" },
        ],
        instructions: [
          "Slice beef into thin strips about 2 inches wide. Thread onto wooden skewers.",
          "In a bowl, combine ground peanuts, cayenne pepper, onion powder, garlic powder, ginger powder, paprika, crushed bouillon cube, and salt to make the yaji spice.",
          "Brush skewers generously with vegetable oil on all sides.",
          "Coat the oiled skewers heavily in the yaji spice mix, pressing the spice into the meat.",
          "Grill over high heat (or under a broiler) for 3-4 minutes per side until charred and cooked through.",
          "Serve immediately with sliced onions, tomatoes, and extra yaji sprinkled on top.",
        ],
        savedBy: [],
        createdAt: Date.now() - 1000,
      },
      {
        title: "Kenkey & Grilled Fish",
        description: "A traditional Ghanaian dish of fermented corn dough served with perfectly grilled tilapia and a fiery pepper sauce.",
        imageUrl: "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?w=800",
        country: "Ghana",
        countryFlag: "🇬🇭",
        chefId,
        tags: ["Halal", "Protein"],
        category: "Dinner",
        rating: 4.5,
        reviewCount: 892,
        prepTime: 600,
        cookTime: 1800,
        servings: 4,
        ingredients: [
          { name: "Ga kenkey", amount: "4 balls" },
          { name: "Whole tilapia", amount: "2 large" },
          { name: "Fresh chilli peppers", amount: "6" },
          { name: "Tomatoes", amount: "4 medium" },
          { name: "Onions", amount: "2 large" },
          { name: "Ginger", amount: "1 inch piece" },
          { name: "Lemon juice", amount: "2 tbsp" },
          { name: "Salt", amount: "to taste" },
        ],
        instructions: [
          "Clean the tilapia, score both sides with a knife, and season with salt and lemon juice.",
          "Grill the fish over medium-high charcoal heat for 8-10 minutes per side until the skin is crispy.",
          "Blend the chilli peppers, tomatoes, onions, and ginger together until chunky for the pepper sauce.",
          "Season the pepper sauce with salt. You can serve it raw or lightly heat it.",
          "Unwrap the kenkey balls and serve alongside the grilled fish and pepper sauce.",
        ],
        savedBy: [],
        createdAt: Date.now() - 2000,
      },
      {
        title: "Short Ribs & Polenta",
        description: "Slow-braised beef short ribs falling off the bone, served over creamy parmesan polenta with a rich red wine jus.",
        imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
        country: "England",
        countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        chefId,
        tags: ["Protein"],
        category: "Dinner",
        rating: 4.7,
        reviewCount: 2104,
        prepTime: 1200,
        cookTime: 10800,
        servings: 4,
        ingredients: [
          { name: "Beef short ribs", amount: "3 lbs" },
          { name: "Red wine", amount: "2 cups" },
          { name: "Beef stock", amount: "2 cups" },
          { name: "Polenta", amount: "1 cup" },
          { name: "Parmesan cheese", amount: "1/2 cup" },
          { name: "Butter", amount: "3 tbsp" },
          { name: "Carrots", amount: "2 large" },
          { name: "Celery stalks", amount: "3" },
          { name: "Garlic cloves", amount: "4" },
          { name: "Fresh rosemary", amount: "3 sprigs" },
        ],
        instructions: [
          "Season short ribs generously with salt and pepper. Sear in a hot Dutch oven on all sides until deeply browned. Remove and set aside.",
          "In the same pot, sauté diced carrots, celery, and garlic until softened, about 5 minutes.",
          "Pour in red wine and scrape up all the browned bits from the bottom. Let it reduce by half.",
          "Add beef stock and rosemary. Return the short ribs to the pot. Cover and braise in a 300°F oven for 3 hours.",
          "When ribs are nearly done, bring 4 cups of water to a boil. Slowly whisk in polenta and stir for 20 minutes until creamy.",
          "Stir butter and parmesan into the polenta. Season with salt and pepper.",
          "Plate the polenta, top with a short rib, and spoon over the braising liquid as a jus.",
        ],
        savedBy: [],
        createdAt: Date.now() - 3000,
      },
      {
        title: "French Toast Stack",
        description: "Thick-cut brioche French toast layered with fresh berries, maple syrup, and a dusting of powdered sugar. The perfect weekend brunch.",
        imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800",
        country: "America",
        countryFlag: "🇺🇸",
        chefId,
        tags: ["Vegan"],
        category: "Breakfast",
        rating: 4.3,
        reviewCount: 438,
        prepTime: 600,
        cookTime: 900,
        servings: 2,
        ingredients: [
          { name: "Brioche bread", amount: "4 thick slices" },
          { name: "Eggs", amount: "3 large" },
          { name: "Whole milk", amount: "1/2 cup" },
          { name: "Vanilla extract", amount: "1 tsp" },
          { name: "Cinnamon", amount: "1 tsp" },
          { name: "Butter", amount: "2 tbsp" },
          { name: "Fresh strawberries", amount: "1 cup" },
          { name: "Blueberries", amount: "1/2 cup" },
          { name: "Maple syrup", amount: "1/4 cup" },
          { name: "Powdered sugar", amount: "for dusting" },
        ],
        instructions: [
          "Whisk together eggs, milk, vanilla extract, and cinnamon in a shallow bowl.",
          "Dip each brioche slice into the egg mixture, letting it soak for 15 seconds per side.",
          "Melt butter in a non-stick skillet over medium heat.",
          "Cook each slice for 3 minutes per side until golden brown and slightly crispy.",
          "Stack the French toast on a plate, layering fresh strawberries and blueberries between each slice.",
          "Drizzle with maple syrup and dust with powdered sugar before serving.",
        ],
        savedBy: [],
        createdAt: Date.now() - 4000,
      },
      {
        title: "Crème Brûlée",
        description: "Silky vanilla custard with a perfectly caramelised sugar crust that cracks under your spoon. A timeless French classic.",
        imageUrl: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800",
        country: "France",
        countryFlag: "🇫🇷",
        chefId,
        tags: ["Vegan"],
        category: "Desserts",
        rating: 4.9,
        reviewCount: 3276,
        prepTime: 900,
        cookTime: 2700,
        servings: 4,
        ingredients: [
          { name: "Heavy cream", amount: "2 cups" },
          { name: "Egg yolks", amount: "5 large" },
          { name: "Granulated sugar", amount: "1/2 cup" },
          { name: "Vanilla bean", amount: "1 whole" },
          { name: "Salt", amount: "pinch" },
          { name: "Demerara sugar", amount: "4 tbsp" },
        ],
        instructions: [
          "Preheat oven to 325°F. Split the vanilla bean lengthwise and scrape out the seeds.",
          "Heat cream with vanilla seeds and pod in a saucepan until it just begins to simmer. Remove from heat.",
          "Whisk egg yolks and granulated sugar together until pale and thick.",
          "Slowly pour the hot cream into the yolks while whisking constantly to temper the eggs.",
          "Strain through a fine sieve into ramekins. Place ramekins in a baking dish and fill with hot water halfway up the sides.",
          "Bake for 40-45 minutes until set but still slightly wobbly in the centre. Chill for at least 4 hours.",
          "Sprinkle demerara sugar evenly on top and torch until caramelised. Let it harden for 1 minute before serving.",
        ],
        savedBy: [],
        createdAt: Date.now() - 5000,
      },
      {
        title: "Açaí Smoothie Bowl",
        description: "A thick, vibrant purple açaí bowl topped with granola, sliced banana, coconut flakes, and a drizzle of honey. Refreshing and energising.",
        imageUrl: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800",
        country: "Jamaica",
        countryFlag: "🇯🇲",
        chefId,
        tags: ["Vegan", "Protein"],
        category: "Breakfast",
        rating: 4.4,
        reviewCount: 761,
        prepTime: 300,
        cookTime: 0,
        servings: 1,
        ingredients: [
          { name: "Frozen açaí packet", amount: "1 (100g)" },
          { name: "Frozen banana", amount: "1 large" },
          { name: "Frozen mixed berries", amount: "1/2 cup" },
          { name: "Almond milk", amount: "1/3 cup" },
          { name: "Granola", amount: "1/4 cup" },
          { name: "Fresh banana", amount: "1/2 sliced" },
          { name: "Coconut flakes", amount: "1 tbsp" },
          { name: "Honey", amount: "1 tbsp" },
          { name: "Chia seeds", amount: "1 tsp" },
        ],
        instructions: [
          "Break the frozen açaí packet into pieces and add to a high-speed blender.",
          "Add frozen banana, mixed berries, and almond milk. Blend until thick and smooth — it should be thicker than a regular smoothie.",
          "Pour the blended mixture into a bowl.",
          "Top one side with granola, another with sliced banana, and sprinkle coconut flakes across the top.",
          "Drizzle honey over everything and finish with a sprinkle of chia seeds. Serve immediately.",
        ],
        savedBy: [],
        createdAt: Date.now() - 6000,
      },
      {
        title: "Pan-Roasted Lobster",
        description: "Succulent lobster tails pan-roasted in garlic butter with a splash of white wine, finished with fresh herbs and lemon.",
        imageUrl: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=800",
        country: "Japan",
        countryFlag: "🇯🇵",
        chefId,
        tags: ["Protein"],
        category: "Dinner",
        rating: 4.8,
        reviewCount: 1982,
        prepTime: 900,
        cookTime: 720,
        servings: 2,
        ingredients: [
          { name: "Lobster tails", amount: "2 large" },
          { name: "Unsalted butter", amount: "4 tbsp" },
          { name: "Garlic cloves", amount: "4 minced" },
          { name: "White wine", amount: "1/4 cup" },
          { name: "Fresh parsley", amount: "2 tbsp chopped" },
          { name: "Lemon", amount: "1" },
          { name: "Olive oil", amount: "2 tbsp" },
          { name: "Salt and pepper", amount: "to taste" },
        ],
        instructions: [
          "Split lobster tails in half lengthwise with a sharp knife. Season the flesh with salt and pepper.",
          "Heat olive oil in a large skillet over high heat until it just begins to smoke.",
          "Place lobster tails flesh-side down and sear for 3 minutes until the edges turn golden and opaque.",
          "Flip the tails shell-side down. Add butter and minced garlic to the pan. Baste the lobster with the melting garlic butter for 2 minutes.",
          "Pour in the white wine and let it sizzle and reduce for 1 minute.",
          "Remove from heat, squeeze fresh lemon juice over the lobster, and garnish with chopped parsley. Serve immediately.",
        ],
        savedBy: [],
        createdAt: Date.now() - 7000,
      },
    ];

    for (const recipe of sampleRecipes) {
      await ctx.db.insert("recipes", recipe);
    }

    return `Seeded ${sampleRecipes.length} recipes`;
  },
});

function flagEmojiFromCode(code: string): string {
  return code
    .toUpperCase()
    .split("")
    .map((c) => String.fromCodePoint(0x1f1e6 - 65 + c.charCodeAt(0)))
    .join("");
}

const COUNTRY_LIST: { name: string; code: string }[] = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Argentina", code: "AR" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Bangladesh", code: "BD" },
  { name: "Belgium", code: "BE" },
  { name: "Brazil", code: "BR" },
  { name: "Bulgaria", code: "BG" },
  { name: "Cambodia", code: "KH" },
  { name: "Canada", code: "CA" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Egypt", code: "EG" },
  { name: "England", code: "GB" },
  { name: "Ethiopia", code: "ET" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR" },
  { name: "Hungary", code: "HU" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Ivory Coast", code: "CI" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO" },
  { name: "Kenya", code: "KE" },
  { name: "South Korea", code: "KR" },
  { name: "Lebanon", code: "LB" },
  { name: "Malaysia", code: "MY" },
  { name: "Mexico", code: "MX" },
  { name: "Morocco", code: "MA" },
  { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nigeria", code: "NG" },
  { name: "Norway", code: "NO" },
  { name: "Pakistan", code: "PK" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Scotland", code: "GB" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Singapore", code: "SG" },
  { name: "South Africa", code: "ZA" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syria", code: "SY" },
  { name: "Taiwan", code: "TW" },
  { name: "Thailand", code: "TH" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "America", code: "US" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Wales", code: "GB" },
  { name: "Zimbabwe", code: "ZW" },
  { name: "Armenia", code: "AM" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahrain", code: "BH" },
  { name: "Belarus", code: "BY" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Cameroon", code: "CM" },
  { name: "Costa Rica", code: "CR" },
  { name: "Ecuador", code: "EC" },
  { name: "Estonia", code: "EE" },
  { name: "Georgia", code: "GE" },
  { name: "Guatemala", code: "GT" },
  { name: "Honduras", code: "HN" },
  { name: "Iceland", code: "IS" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Latvia", code: "LV" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Mongolia", code: "MN" },
  { name: "Nepal", code: "NP" },
  { name: "North Macedonia", code: "MK" },
  { name: "Oman", code: "OM" },
  { name: "Panama", code: "PA" },
  { name: "Paraguay", code: "PY" },
  { name: "Qatar", code: "QA" },
  { name: "Rwanda", code: "RW" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Sudan", code: "SD" },
  { name: "Tanzania", code: "TZ" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Uganda", code: "UG" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Yemen", code: "YE" },
];

// Run via: npx convex run seed:seedCountries
export const seedCountries = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("countries").collect();
    for (const row of existing) {
      await ctx.db.delete(row._id);
    }
    for (const { name, code } of COUNTRY_LIST) {
      await ctx.db.insert("countries", {
        name,
        code,
        flagEmoji: flagEmojiFromCode(code),
      });
    }
    return `Seeded ${COUNTRY_LIST.length} countries`;
  },
});
